image: fedora/latest
packages:
  - elixir
  - gcc-c++
  - openssl-devel
  - zlib-devel
  - gperf
  - cmake
  - tar
sources:
  - https://github.com/prtngn/ex_tdlib
tasks:
- build-deps: |
    cd ex_tdlib
    mix local.hex --force
    mix deps.get
    mix deps.compile
- build: |
    cd ex_tdlib
    mix compile
- test: |
    cd ex_tdlib
    mix test
